Repository Software-Process/Software-Process.github.io, pull requests merged in 2018-03, with the labels that each got.

#113 Added user page and edit user page [#88]
  .gitignore
  app.js
  package-lock.json
  public/images/default1.png
  public/images/default2.png
  public/images/default3.png
  public/images/default4.png
  public/images/default5.png
  public/stylesheets/index.css
  routes/editUserPage.js
  routes/userPage.js
  views/edituserpage.hbs
  views/partials/header.hbs
  views/userpage.hbs
Labels: CSS, HTML

#114 Replaced Jasmine/Karma framework by Mocha. [#90].
  .travis.yml
  karma.conf.js
  package-lock.json
  package.json
  test/testingSpec.js
Labels: Refactoring, Task, Testing

#116 Implementing unit tests for database testing [#90]
  test/questionSpec.js
  test/questionsSpec.js
Labels: Task, Testing

#117 [#66] Front end refactoring involved ensuring consistent design across pages
  app.js
  package-lock.json
  package.json
  public/images/lock.png
  public/javascripts/questionFrontEnd.js
  public/stylesheets/index.css
  public/stylesheets/indexstyle.css
  public/stylesheets/question.css
  public/stylesheets/signin.css
  public/stylesheets/standardstyle.css
  public/stylesheets/style.css
  public/stylesheets/userpagestyle.css
  views/aboutus.hbs
  views/edituserpage.hbs
  views/index.hbs
  views/partials/footer.hbs
  views/partials/header.hbs
  views/question-prompt.hbs
  views/question.hbs
  views/signIn.hbs
  views/userpage.hbs
Labels: CSS, HTML, Refactoring

#118 User login system. [#93, #94, #95, #96, #97]
  app.js
  models/user.js
  package-lock.json
  package.json
  routes/editUserPage.js
  routes/index.js
  routes/loginRegister.js
  routes/question-prompt.js
  routes/userPage.js
  views/edituserpage.hbs
  views/index.hbs
  views/partials/header.hbs
  views/signIn.hbs
  views/userpage.hbs
Labels: Express, MongoDB, Node.js, Task

#119 Implementing new unit tests for the database and javascript files [#90]
  public/javascripts/question-prompt.js
  public/javascripts/questionFrontEnd.js
  test/question-promptSpec.js
  test/questionFrontEndSpec.js
  test/questionSpec.js
  test/questionsSpec.js
  test/userSpec.js
Labels: Database, JavaScript, Task, Testing

#142 Merge kjanei/code-styling into master
  DataManager.js
  models/question.js
  models/reply.js
  mongo_registration_database/registration_add_documents.js
  mongo_registration_database/registration_collection_creation.js
  mongo_registration_database/registration_query.js
  public/javascripts/questionFrontEnd.js
  routes/aboutUs.js
  routes/editUserPage.js
  routes/index.js
  routes/loginRegister.js
  routes/question-prompt.js
  routes/question.js
  routes/questions.js
  routes/userPage.js
  routes/users.js
  views/aboutus.hbs
  views/edituserpage.hbs
  views/index.hbs
  views/question-prompt.hbs
  views/question.hbs
  views/signIn.hbs
  views/userpage.hbs
Labels: CSS, HTML, JavaScript, Node.js, Refactoring

#150 Login validation, voting and other bug fixes. [#45. #144. #145]
  app.js
  models/question.js
  package-lock.json
  package.json
  routes/aboutUs.js
  routes/index.js
  routes/loginRegister.js
  routes/question.js
  views/aboutus.hbs
  views/edituserpage.hbs
  views/index.hbs
  views/partials/header.hbs
  views/question.hbs
  views/signIn.hbs
Labels: Bug, MongoDB, Node.js

#160 Frontend implementation of user ranking page [#135]
  app.js
  public/stylesheets/userrankpagestlye.css
  routes/userRankPage.js
  views/partials/header.hbs
  views/userRankPage.hbs
Labels: CSS, HTML

#162 Login and register page validation. [#145]
  public/javascripts/question-prompt.js
  routes/loginRegister.js
  views/companypage.hbs
  views/edituserpage.hbs
  views/index.hbs
  views/jobpage.hbs
  views/jobposting.hbs
  views/question.hbs
  views/signIn.hbs
  views/userRankPage.hbs
  views/userpage.hbs
Labels: Express, Node.js

#164 Tags can be selected in question-prompt page and seen in user page [#130]
  public/stylesheets/question-prompt.css
  public/stylesheets/userpagestyle.css
  views/question-prompt.hbs
  views/userRankPage.hbs
  views/userpage.hbs
Labels: CSS, HTML

#165 Added backend functionality for tags [#136]
  models/question.js
  models/user.js
  public/javascripts/tagLimit.js
  routes/question-prompt.js
  routes/question.js
  views/question-prompt.hbs
  views/question.hbs
  views/userpage.hbs
Labels: CSS, Database, HTML, JavaScript, Task

#166 Task/Bug #45: Finished Accepting/rejecting of answers both frontend/backend
  app.js
  models/history.js
  models/question.js
  package-lock.json
  package.json
  public/stylesheets/question.css
  routes/question-prompt.js
  routes/question.js
  views/question.hbs
Labels: Bug, JavaScript, Node.js

#169 [#151] [#123] Job description page
  models/jobs.js
  routes/jobPage.js
  routes/jobPostingPage.js
  views/jobdescription.hbs
  views/jobpage.hbs
  views/jobposting.hbs
Labels: CSS, HTML, JavaScript, Node.js, Task

#167 Company registration and approval. [#152]
  routes/companyAccount.js
  routes/loginRegister.js
  views/companypage.hbs
  views/question-prompt.hbs
  views/signIn.hbs
Labels: JavaScript, Node.js, Task

#168 Task #63 User story #45 : Finished the tasks that were not passing the acceptances testing
  models/question.js
  models/reply.js
  public/javascripts/questionFrontEnd.js
  routes/question.js
  views/question.hbs
Labels: Bug, CSS, HTML, JavaScript, Node.js

#171 User icon implementation. [#98]
  models/user.js
  routes/loginRegister.js
  views/index.hbs
  views/userpage.hbs
Labels: MongoDB, Task

#172 [#163] Fixed the external user page statistics
  routes/userPage.js
  views/userpage.hbs
Labels: Enhancement, HTML, Node.js, Task

#175 Color change is now reflected on the user page. [#146]
  views/userpage.hbs
Labels: Bug, HTML

#176 [#131] Fixed tag sorting for questions
  package.json
  public/javascripts/tagFilter.js
  public/stylesheets/indexstyle.css
  routes/index.js
  views/index.hbs
Labels: CSS, Enhancement, Node.js, Task

#174 Answers accepted/rejected notification. [#122]
  models/user.js
  public/stylesheets/standardstyle.css
  routes/question-prompt.js
  routes/question.js
  routes/userPage.js
  views/index.hbs
  views/partials/header.hbs
  views/userpage.hbs
Labels: MongoDB, Node.js, Task

#183 [#181] Fixed the validation leading to app crashing
  routes/loginRegister.js
Labels: Bug, MongoDB, Node.js

#184 [#180] Fixed all of the redirect issue for question prompt
  routes/index.js
  routes/questionPrompt.js
  views/index.hbs
  views/questionPrompt.hbs
Labels: Bug, MongoDB, Node.js

#185 Implemented backend for user rank page [#135]
  models/question.js
  package.json
  public/stylesheets/userrankpagestlye.css
  routes/index.js
  routes/loginRegister.js
  routes/question.js
  routes/userRankPage.js
  views/jobpage.hbs
  views/question.hbs
  views/userRankPage.hbs
Labels: CSS, HTML, JavaScript

#187 Replaced placeholder tag scores in userpage.hbs [#186]
  views/userpage.hbs
Labels: Bug, HTML
